### ISSUE TITLE
Feature request: Saving in .ron format

### ISSUE THREAD

**Issue by pinkponk** [hankjordan/bevy_save#1]
For noobies like me it would be far easier to understand what is in the save file if it is a known format like .ron or .json. Adding an example for this would be nice.

**Comment by hankjordan** [comment]
I'd like to support this, but I am not quite sure that the API would look like.
In the mean time, this is possible to do manually via [get_save_file](https://docs.rs/bevy_save/latest/bevy_save/fn.get_save_file.html) and [World::serialize](https://docs.rs/bevy_save/latest/bevy_save/trait.WorldSaveableExt.html#tymethod.serialize) / [World::deserialize](https://docs.rs/bevy_save/latest/bevy_save/trait.WorldSaveableExt.html#tymethod.deserialize).

**Comment by hankjordan** [comment]
I have added [an example](https://github.com/hankjordan/bevy_save/blob/master/examples/json.rs) showing how to use  `bevy_save` with a text-based format.

Supporting a custom format with `World::save` and `World::load` is still planned.

**Comment by hankjordan** [comment]
Closed as completed via [#a01ed0](https://github.com/hankjordan/bevy_save/commit/a01ed0dccefcf05fc47dc0bd06a2afb26132b33b), it is now possible to use the `AppSaver` and `AppLoader` to specify a custom save file format, I have updated the examples accordingly.
