### ISSUE TITLE
[Bug] Entity mapping for parent/children hierarchy does not work if entities are deleted first

### ISSUE THREAD

**Issue by robertdodd** [hankjordan/bevy_save#13]
I found a bug with mapping references to entity ids. If you delete the entities in your world before loading, then re-load, the world will contain invalid entity IDs where there was an entity pointer. It happens with `Parent` components and custom components with an `Entity` property implementing `MapEntities`.

After loading the new `Parent` component points to a non-existent entity.

I've included an example to reproduce below.

**What else I have tried**

When it first happend with `Parent`/`Children`, I tried implementing `MapEntities` in a component to hold the relationship instead. The same issue occurred, after loading it held an invalid ID.

I noticed that my component's `map_entities` function was never called. I put a `println` in it's `map_entities` and never saw it in the console.

EDIT: with `MappingMode::Strict`, the below example crashes after load from a heirarchy assertion in `bevy`.

**What I want to try next, but haven't tried yet**

Next, I'll try to debug print the `EntityMap` so I can see what entities it contains after loading, as well as the code that calls the `ReflectMapEntities` functions to see what's happening.

**What else I considered**

[moonshine_save](https://github.com/Zeenobit/moonshine_save) uses a custom resource to expose the entity id mappings after load, and components can implement a `FromLoaded` to set their ID's after load.

I'm not too sure about how `MapEntities` works, but if I couldn't get it working I was considering implementing a similar thing here.

**Example**

Modified `examples/main.rs`, where I spawn a child entity with a `Head` component on the player.

To reproduce: Hit `ENTER` to save, then `R` to delete all players, then `BACKSPACE` to load. Hit `P` to print debug info about all heads, and it'll show that the head's `Parent` entity does not exist. It will still point to the original parent ID from before you deleted them.

```
use bevy::prelude::*;
use bevy_inspector_egui::quick::WorldInspectorPlugin;
use bevy_save::prelude::*;

#[derive(Component, Reflect, Default)]
#[reflect(Component)]
pub struct Player;

#[derive(Component, Reflect, Default)]
#[reflect(Component)]
pub struct Head;

fn setup(mut commands: Commands) {
    commands
        .spawn((SpatialBundle::default(), Player))
        .with_children(|p| {
            p.spawn(Head);
        });

    // to reproduce the error, hit the following keys:
    // P         - Print debug info about heads and check their parent exists
    // ENTER     - Save
    // R         - Reset, delete all player entities
    // BACKSPACE - Load
    // P         - Print head info <== head will have an invalid parent
    println!("Controls:");
    println!("P: to print debug info on `Head` entities and to validate their parent exists");
    println!("R: to recursively delete all `Player` entities");
    println!("ENTER: Save");
    println!("BACKSPACE: Load");
}

fn interact(world: &mut World) {
    let keys = world.resource::<Input<KeyCode>>();

    if keys.just_released(KeyCode::Return) {
        info!("Save");
        world.save("example").expect("Failed to save");
    } else if keys.just_released(KeyCode::Back) {
        info!("Load");
        world.load("example").expect("Failed to load");
    } else if keys.just_pressed(KeyCode::E) {
        info!("Info");
        for entity in world.iter_entities() {
            info!("Entity: {:?}", entity.id());
            for component_id in entity.archetype().components() {
                if let Some(component) = world.components().get_info(component_id) {
                    info!("  {:?}: {:?}", entity.id(), component.name());
                }
            }
        }
    }
}

fn handle_keys(
    keys: Res<Input<KeyCode>>,
    head_query: Query<(Entity, &Parent)>,
    despawn_query: Query<Entity, With<Player>>,
    mut commands: Commands,
) {
    // Print head debug info, check that all heads have a valid parent
    if keys.just_released(KeyCode::P) {
        println!("{} Heads", head_query.iter().len());
        for (entity, parent) in &head_query {
            println!("  Head {:?} has parent: {:?}", entity, parent.get());
            if commands.get_entity(parent.get()).is_none() {
                println!("    X - Head parent does not exist!");
            } else {
                println!("    Ok - Head parent exists, all good")
            }
        }
    }

    // Reset, delete all entities
    if keys.just_released(KeyCode::R) {
        for entity in &despawn_query {
            commands.entity(entity).despawn_recursive();
        }
    }
}

fn main() {
    App::new()
        .add_plugins(DefaultPlugins.build().set(AssetPlugin {
            asset_folder: "examples/assets".to_owned(),
            ..default()
        }))
        // Inspector
        .add_plugin(WorldInspectorPlugin::new())
        // Bevy Save
        .add_plugins(SavePlugins)
        // Uncomment this and the app will crash after load, due to a `bevy` assertion on the parent/child heirarchy
        // .insert_resource(AppMappingMode::new(MappingMode::Strict))
        .register_saveable::<Player>()
        .register_saveable::<Parent>()
        .register_saveable::<Head>()
        .register_saveable::<Children>()
        .register_type::<Head>()
        .register_type::<Player>()
        .add_startup_system(setup)
        .add_system(interact)
        .add_system(handle_keys)
        .run();
}
```

**How I've been using `bevy_save`**

Not relevant to the issue, but I've been using `bevy_save` in a level editor for `Undo` + `Redo` behavior -- the rolbacks are a really great feature.

**Comment by hankjordan** [comment]
Unfortunately, this is not an easy problem to solve and will require breaking changes to the save format.

In the mean time, it is possible to work around by ditching `World::load` when working with any components that contain entities and providing an`EntityMap` to `Applier<Snapshot>` manually.

**Comment by robertdodd** [comment]
Thanks for the reply!

I had trouble applying an `EntityMap` manually, but I made a fork and fixed it for myself there.

The changes I made would be breaking, I changed `SaveableEntity` to support the full entity ID, changed how the `EntityMap` is filled and applied and also called `set_parent` on all loaded entities that had a `Parent`.

[You can have a look at the changes here](https://github.com/hankjordan/bevy_save/compare/master...robertdodd:bevy_save:fix/13-fix-entity-mapping) if you want.

`Children` was a problem and still doesn't work -- I ended up excluding it from my saves. It may contain entities that weren't included in the save (because of despawning and filtering) and filtering a `Children` was harder than I thought. `Parent` always worked because it was a single relationship, so I stuck with that.

**Comment by hankjordan** [comment]
Looks great. More or less exactly what I would have done. I will put together a PR and get this merged.

Though I am curious why you need to call `set_parent` here - does that populate `Children` for you?

**Comment by robertdodd** [comment]
> Looks great. More or less exactly what I would have done. I will put together a PR and get this merged.

Thanks! I wasn't certain about the other contexts `bevy_save` is used in, such as the third-party crate support, and I've only tested it for real in scenarios where I despawn components first.

> Though I am curious why you need to call set_parent here - does that populate Children for you?

Yes, that was my workaround for not including `Children` in the save.

If you don't call `set_parent`, bevy complains about broken hierarchies. It may only happen when `GlobalTransforms` are involved, I can't remember for sure, so it may be worth adding transforms to the hierarchy example.
