### ISSUE TITLE
Problems with using RON crate

### ISSUE THREAD

**Issue by dmlary** [hankjordan/bevy_save#14]
Based off the JSON example using the RON crate should work, but unlike the JSON implementation `ron::de::from_reader` requires a type that satisfies `de::DeserializeOwned`:

```rust
impl Loader for RonLoader {
    fn deserializer<'r, 'de>(&self, reader: Reader<'r>) -> IntoDeserializer<'r, 'de> {
        let deserializer = ron::de::from_reader(reader).unwrap();
        IntoDeserializer::erase(deserializer)
    }
}
```

```txt
error[E0282]: type annotations needed
   --> src/bin/editor.rs:904:13
    |
904 |         let deserializer = ron::de::from_reader(reader).unwrap();
    |             ^^^^^^^^^^^^
    |
help: consider giving `deserializer` an explicit type
    |
904 |         let deserializer: /* Type */ = ron::de::from_reader(reader).unwrap();
    |                         ++++++++++++
```

However, when I try to use `Snapshot` as the type, compilation fails because `serde::Deserialize` is not implemented for `Snapshot`.

```rust
impl Loader for RonLoader {
    fn deserializer<'r, 'de>(&self, reader: Reader<'r>) -> IntoDeserializer<'r, 'de> {
        let deserializer: Snapshot = ron::de::from_reader(reader).unwrap();
        IntoDeserializer::erase(deserializer)
    }
}
```

```txt
error[E0277]: the trait bound `for<'de> bevy_save::Snapshot: Deserialize<'de>` is not satisfied
   --> src/bin/editor.rs:904:38
    |
904 |         let deserializer: Snapshot = ron::de::from_reader(reader).unwrap();
    |                                      ^^^^^^^^^^^^^^^^^^^^ the trait `for<'de> Deserialize<'de>` is not implemented for `bevy_save::Snapshot`
    |
    = help: the following other types implement trait `Deserialize<'de>`:
              &'a [u8]
              &'a serde_json::raw::RawValue
              &'a std::path::Path
              &'a str
              ()
              (T0, T1)
              (T0, T1, T2)
              (T0, T1, T2, T3)
            and 389 others
    = note: required for `bevy_save::Snapshot` to implement `DeserializeOwned`
note: required by a bound in `from_reader`
   --> /Users/dmlary/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ron-0.8.0/src/de/mod.rs:72:8
    |
72  |     T: de::DeserializeOwned,
    |        ^^^^^^^^^^^^^^^^^^^^ required by this bound in `from_reader`
```

Is there any way to work around this?

**Comment by hankjordan** [comment]
> Based off the JSON example using the RON crate should work, but unlike the JSON implementation `ron::de::from_reader` requires a type that satisfies `de::DeserializeOwned`:
> 
> ```rust
> impl Loader for RonLoader {
>     fn deserializer<'r, 'de>(&self, reader: Reader<'r>) -> IntoDeserializer<'r, 'de> {
>         let deserializer = ron::de::from_reader(reader).unwrap();
>         IntoDeserializer::erase(deserializer)
>     }
> }
> ```
> 
> ```
> error[E0282]: type annotations needed
>    --> src/bin/editor.rs:904:13
>     |
> 904 |         let deserializer = ron::de::from_reader(reader).unwrap();
>     |             ^^^^^^^^^^^^
>     |
> help: consider giving `deserializer` an explicit type
>     |
> 904 |         let deserializer: /* Type */ = ron::de::from_reader(reader).unwrap();
>     |                         ++++++++++++
> ```
> 
> However, when I try to use `Snapshot` as the type, compilation fails because `serde::Deserialize` is not implemented for `Snapshot`.
> 
> ```rust
> impl Loader for RonLoader {
>     fn deserializer<'r, 'de>(&self, reader: Reader<'r>) -> IntoDeserializer<'r, 'de> {
>         let deserializer: Snapshot = ron::de::from_reader(reader).unwrap();
>         IntoDeserializer::erase(deserializer)
>     }
> }
> ```

You don't actually deserialize any type inside of the Saver / Loader trait. You simply return something that can be turned into a Serializer / Deserializer that may later serialize / deserialize a given type.

So this is what a RON Saver might look like:
```rust
struct RONSaver;

impl Saver for RONSaver {
    fn serializer<'w>(&self, writer: Writer<'w>) -> IntoSerializer<'w> {
        IntoSerializer::erase(ron::ser::Serializer::new(writer, Some(ron::ser::PrettyConfig::default())).expect("Failed to create Serializer"))
    }
}
```

Loader would likely be impossible with the current implementation - the RON crate would need to provide a `Deserializer::from_reader` method to make it work.

**Comment by dmlary** [comment]
> the RON crate would need to provide a Deserializer::from_reader method to make it work.

Ah, I see, `ron::de::from_reader` (the only `from_reader` available) is for deserializing a specific type from a reader.  You need a deserializer for a generic type.

With that I was able to find this workaround for my case.  Not using `Loader` trait:
```rust
    let bytes = std::fs::read(path.clone()).context("failed to read map file")?;
    let mut deserializer =
        ron::de::Deserializer::from_bytes(&bytes).context("failed to create ron deserializer")?;
    let registry = world.resource::<AppTypeRegistry>().clone();
    let reg = registry.read();
    let snapshot_deserializer = SnapshotDeserializer::new(&reg);
    let snap = snapshot_deserializer
        .deserialize(&mut deserializer)
        .context("failed to deserialize map data")?;
    snap.into_applier(world)
        .apply()
        .map_err(|e| anyhow!("{:#?}", e))
        .context("failed to apply map snapshot")?;
```

**Comment by hankjordan** [comment]
Nothing I can do about this, I thought the refactor might eliminate this issue but it didn't.

**Comment by hankjordan** [comment]
Works now

**Comment by dmlary** [comment]
Oh, that's spectacular! Thank you!
