### ISSUE TITLE
WASM target fails to compile

### ISSUE THREAD

**Issue by hankjordan** [hankjordan/bevy_save#18]
It would be nice if the features which did work on WASM were able to be used. My understanding is that this crate cannot be built for WASM targets currently because the `Default` for `AppBackend` hasn't been implemented yet. It's clear that this is the commented-out TODO code. For me, it would be preferable if this code panicked if used rather than preventing compilation entirely.

_Originally posted by @MeoMix in https://github.com/hankjordan/bevy_save/issues/4#issuecomment-1679125540_

**Comment by MeoMix** [comment]
Thank you!
