### ISSUE TITLE
Finish implementation of WASM backend

### ISSUE THREAD

**Issue by MeoMix** [hankjordan/bevy_save#24]
I'm updating to the latest bevy_save and it's going well enough. I'm unable to use the default WebStorage backend implementation because I rely on compressing save state prior to writing to local storage. This is especially important because local storage maxes out at 5mb. I've found it pretty easy to exceed that when creating a 2D tile map where each tile is an entity.

It's fine if you consider it out of scope. I think it's reasonable to see it as such and it's easy enough to implement a custom backend, but I thought I'd highlight my use case just to be sure.

**Comment by hankjordan** [comment]
Not out of scope.

The current WASM implementation is a stop-gap. The way it is implemented a custom Format will not work on WASM at the moment - but I plan to fix this soon.

**Comment by MeoMix** [comment]
Sounds good. Yeah, I just ran into that. It was a bit of a surprise seeing the `load` method accept a generic `F: Format` but then not use it. I was scratching my head for a second wondering why my types were mad, but easy enough to fix.
