### ISSUE TITLE
Is this the expected way of calling `extract_entities`  with a filtered query?

### ISSUE THREAD

**Issue by MeoMix** [hankjordan/bevy_save#26]
Heyo.

Previously, I had code which looked like this:

```rust

fn create_save_snapshot(world: &mut World) -> Option<Vec<u8>> {
    let mut buffer: Vec<u8> = Vec::new();
    let mut serde = Serializer::new(&mut buffer);
    // Persistent entities must have an Id marker because Id is fit for uniquely identifying across sessions.
    let mut id_query = world.query_filtered::<Entity, With<Id>>();

    let snapshot = Snapshot::builder(world)
        .extract_entities(id_query.iter(world))
        .extract_all_resources()
        .build();
        
       ...
```

I am trying to express this using a custom `Pipeline`.

I see that `SnapshotBuilder` exposes only immutable access to `World` which means I am unable to invoke `query_filtered` from within `capture_seed`. I wanted to confirm that the expected way of handling this is something like:

```rust
struct SaveLoadPipeline {
    key: String,
    id_entities: Vec<Entity>,
}

impl SaveLoadPipeline {
    pub fn new(id_entities: Vec<Entity>) -> Self {
        Self {
            key: LOCAL_STORAGE_KEY.to_string(),
            id_entities
        }
    }
}

pub fn load(world: &mut World) -> bool {
    let mut id_query = world.query_filtered::<Entity, With<Id>>();
    let id_entities = id_query.iter(world).collect();

    world.load(SaveLoadPipeline::new(id_entities)).is_ok()
}

impl Pipeline for SaveLoadPipeline {
    type Backend = CompressedWebStorageBackend;
    type Format = DefaultDebugFormat;

    type Key<'a> = &'a str;

    fn key(&self) -> Self::Key<'_> {
        &self.key
    }

    fn capture_seed(&self, builder: SnapshotBuilder) -> Snapshot {
        builder
            .extract_entities(self.id_entities.iter().cloned())
            .extract_all_resources()
            .build()
    }

    // TODO: Confirm that lack of DespawnMode::None and MappingMode::Strict is OK
    // https://github.com/hankjordan/bevy_save/issues/25
    fn apply_seed(&self, world: &mut World, snapshot: &Snapshot) -> Result<(), bevy_save::Error> {
        snapshot.applier(world).apply()
    }
}
```

This approach seems okay. My concern is that, in my scenario, this results in cloning tens of thousands of entities rather than using the iterator directly, but Entity is cheap to clone so I'm not expecting major issues.

 An alternative could be maintaining the result of the query in a resource and accessing the resource immutably from within `capture_seed`. This seems like a lot of overhead, but would make the save operation faster. That overhead didn't seem worth it right now.
 
I didn't think it was reasonable/possible to preserve the iterator on `Pipeline` as that would get lifetimes involved significantly.

Thanks

**Comment by hankjordan** [comment]
I think you could do better if you store it in a resource (so you don't need to re-create it every time you load) but other than that it looks right. Not sure if it matters. Might not work with "as_readonly" though
