### ISSUE TITLE
Persistent ID / entity mapping

### ISSUE THREAD

**Issue by MeoMix** [hankjordan/bevy_save#27]
Heyo.

I would appreciate a minimal example of how to save world state in such a way that it is fit for reuse across sessions:

Current documentation correctly calls out `Entity` as not being fit for persistence across sessions. I've introduced an `Id` component to my entities. It's a struct containing a `Uuid`:

```rust

#[derive(Resource, Debug, Default)]
pub struct IdMap(pub HashMap<Id, Entity>);

// Id is needed because Entity isn't fit for use across sessions, i.e. save state, refresh page, load state.
#[derive(Component, Debug, Eq, PartialEq, Hash, Clone, Serialize, Deserialize, Reflect)]
#[reflect(Component)]
pub struct Id(pub Uuid);

impl Default for Id {
    fn default() -> Self {
        Id(Uuid::new_v4())
    }
}
```

I understand that I am supposed to apply an `entity_map` to my `Snapshot` `applier`, but it's not clear to me what to do afterward.

If I create a mapping between Entity and Uuid, write to storage, and then refresh the page... what is supposed to happen when I load from storage? Am I supposed to have a way of reversing the mapping - potentially by persisting the map, too? That doesn't seem right because if that were the case then persisting Entity itself would work fine.

Presumably I can't just load the state without transforming it in some way because `Id` is too large of a type to be compatible with `Entity`.

Thanks

**Comment by hankjordan** [comment]
The tile map example shows a little bit on this, are you really sure you need persistent id's though?

**Comment by MeoMix** [comment]
I'm not especially confident, no. How could I become more confident?

As an example, I have an Entity which is able to pick up another Entity and carry it. I haven't been thrilled with parent/child relationships for model state in Bevy and struggled with trying to recreate the parent/child hierarchy after loading persisted world state. So, I kept my state flat and established a relationship between the two entities by storing a unique id on a Component. Originally, I did this with with Entity, but after reading that Entity wasn't safe to use for persistence across sessions I replaced it with `Id`:

#[derive(Component, Debug, PartialEq, Clone, Serialize, Deserialize, Reflect, Default)]
#[reflect(Component)]
pub struct InventoryItem {
    pub parent_id: Id,
}

I then maintain a mapping of Entity to Id and lookup the corresponding Entity as needed.

My understanding is that if I were to persist the relationship using Entity that, when I recreate the world, my relationship would break because when I recreate my world from persisted state the newly created Entities may have new entity ids.

Is this an incorrect assumption? Is using `MapEntities` a way to provide a stronger guarantee that I won't break my relationship when reloading state?

**Comment by hankjordan** [comment]
Using entities would probably work for this. It's not that entities are a bad way of storing id, just that they don't work as a _permanent_ id since they usually change after save / load. You should try `MapEntities`, it actually works now.

**Comment by MeoMix** [comment]
Confirmed!

```rust
#[derive(Component, Debug, PartialEq, Clone, Serialize, Deserialize, Reflect, Default)]
#[reflect(Component, MapEntities)]
pub struct AntInventory(pub Option<Entity>);

impl MapEntities for AntInventory {
    fn map_entities(&mut self, entity_mapper: &mut EntityMapper) {
        info!("running!");
        if let Some(entity) = self.0 {
            self.0 = Some(entity_mapper.get_or_reserve(entity));
        }
    }
}
```

allows me to delete all my custom Uuid code.

**Comment by AntonZelenin** [comment]
Hi @MeoMix, could you please explain where entity_mapper gets the mapping from? Is it created automatically by bevy? I tried to search in your project and it seems you do not create the mapping by yourself anywhere in the code

**Comment by AntonZelenin** [comment]
Hi @MeoMix, could you please explain where entity_mapper gets the mapping from? Is it created automatically by bevy? I tried to search in your project and it seems you do not create the mapping by yourself anywhere in the code

**Comment by Chaojimengnan** [comment]
This may be helpful for some people, as we can directly use '#[entities]' on bevy 0.16

```rust
#[derive(Component, Debug, PartialEq, Clone, Serialize, Deserialize, Reflect, Default)]
#[reflect(Component)]
pub struct AntInventory(#[entities] pub Option<Entity>);
```
