### ISSUE TITLE
Was there a technical reason to avoid using `rmp_serde` in the WASM context?

### ISSUE THREAD

**Issue by MeoMix** [hankjordan/bevy_save#29]
Heyo.

I updated to Bevy 0.12.1 today which unblocked my WASM builds and allowed me to test the changes I made to my app to support the new `bevy_save`.

After making the necessary updates, I encountered an error in deserialization:

![image](https://github.com/hankjordan/bevy_save/assets/1380995/84141c7e-ad7e-4b08-a117-8dea1c32835d)

where `StoryTime` looks like:

```rust
#[derive(Resource, Clone, Reflect)]
#[reflect(Resource)]
pub struct StoryTime {
    elapsed_ticks: isize,
    pub is_real_time: bool,
    pub is_real_sun: bool,
    pub latitude: f32,
    pub longitude: f32,
    real_time_offset: isize,
    demo_time_offset: isize,
}
```

After a bit of fussing, I realized that this error went away if I stopped using `rmp_serde` and instead used `serde_json`. The only changes I made to my code to swap between the two were:

```rust

    let mut serde = rmp_serde::Serializer::new(&mut buffer);
    //let mut serde = serde_json::Serializer::new(&mut buffer);

    ...

    let mut deserializer = rmp_serde::Deserializer::new(&data[..]);
    //let mut deserializer = serde_json::Deserializer::from_reader(&data[..]);
```

After these changes, serialization/deserialization work on 0.12.1 just as I'd hope.

More confusingly, I've been happily using `rmp_serde` (w/ Brotli compression) against Bevy 0.11 for the past couple of months (https://github.com/MeoMix/symbiants/blob/48b9120e6ea5877ce06b73be3225330979fb4647/src/save/save_web.rs) without issue.

Is there something I'm not understanding here? Why would updating to latest break my usage of `rmp_serde`? Did you run into a technical reason for using `json_serde` for WASM support in `bevy_save` - or was it merely a stopgap because of slight interface differences between `rmp_serde` and `json_serde` ?

Thanks

**Comment by hankjordan** [comment]
The WASM backend doesn't even work with Format at the moment due to an implementation issue, how are you saving to the browser?

**Comment by hankjordan** [comment]
Also, there was a bug in bevy 0.12.0 which caused a similar error. You might try cargo update and sneaking a peak at your Cargo.lock to confirm you are really on the latest version

**Comment by MeoMix** [comment]
> The WASM backend doesn't even work with Format at the moment due to an implementation issue, how are you saving to the browser?

I created a custom backend by following your examples:

```rust
impl Pipeline for SaveLoadPipeline {
    type Backend = CompressedWebStorageBackend;
    ....
}

#[derive(Default, Resource)]
pub struct CompressedWebStorageBackend;

impl<'a> Backend<&'a str> for CompressedWebStorageBackend {
    fn save<F: Format, T: Serialize>(&self, _key: &str, _value: T) -> Result<(), Error> {
        Err(Error::custom(
            "Not implemented - expected to save by writing snapshot manually for now",
        ))
    }

    fn load<'de, F: Format, T: DeserializeSeed<'de>>(
        &self,
        key: &str,
        seed: T,
    ) -> Result<T::Value, Error> {
        let data = LocalStorage::get::<Vec<u8>>(key).map_err(|e| {
            error!("{}: {:?}", LOAD_ERROR, e);
            Error::custom(LOAD_ERROR)
        })?;

        // Deserialize the data
        //let mut deserializer = rmp_serde::Deserializer::new(&data[..]);
        let mut deserializer = serde_json::Deserializer::from_reader(&data[..]);

        seed.deserialize(&mut deserializer).map_err(Error::loading)
    }
}
```

I've edited out the Brotli compression logic.

> Also, there was a bug in bevy 0.12.0 which caused a similar error. You might try cargo update and sneaking a peak at your Cargo.lock to confirm you are really on the latest version

Hum. I'll do a cargo clean/build to double check, but 0.12.0 had breaking WASM issues related to asset loading that prevented it from loading at all until I updated this morning. So I'm at least reasonably confident that I'm on latest.

**Comment by MeoMix** [comment]
Oh! I see you released a new version 6 hours ago, hah. Maybe that has something to do with it? Checking now

**Comment by MeoMix** [comment]
*sad developer noises* that was it. rmp_serde now works without issue after updating to the latest bevy_save. Sorry for the hassle!

**Comment by hankjordan** [comment]
> LocalStorage::get::<Vec<u8>>(key)

Whatttttt you can do that? No way
Will fix the terrible WASM implementation right away

**Comment by MeoMix** [comment]
> > LocalStorage::get::<Vec>(key)
> 
> Whatttttt you can do that? No way Will fix the terrible WASM implementation right away

It's certainly a nice shorthand, but it's provided by `gloo-storage` and I'm not sure if you'd like the dependency or not.

**Comment by hankjordan** [comment]
`0.13.0` is out with an implementation.
As well as the "brotli" middleware that can be enabled with the `brotli` feature flag:

```rust
use bevy_save::prelude::*;

struct MyPipeline;

impl Pipeline for MyPipeline {
    type Backend = DefaultBackend;
    
    /// This will emit brotli-compressed MessagePack
    type Format = Brotli<DefaultFormat>;
    
    type Key<'a> = &'a str;
    
    fn key(&self) -> Self::Key<'_> {
        "my_pipeline"
    }
}
```
