### ISSUE TITLE
Is it possible not to depend on `bevy_scene`?

### ISSUE THREAD

**Issue by mantou132** [hankjordan/bevy_save#3]
`bevy_scene` has a lot of other bevy dependencies, such as `bevy_render`. I want `bevy_save` to work in games that only use the minimal plugin set.

thanks.

**Comment by hankjordan** [comment]
As of right now, `bevy_save` depends on `DynamicScene` for component serialization and deserialization. I am working on a refactor right now that will also remove this dependency.

It should still be possible to use `bevy_save` even without default plugins - just with some extra compile time.

**Comment by hankjordan** [comment]
Completed as completed via [#68abdf](https://github.com/hankjordan/bevy_save/commit/68abdf9fcb6d332cdd4b7fb05ae28c20eac54542)
