### ISSUE TITLE
Update to Bevy 0.13

### ISSUE THREAD

**Issue by MeoMix** [hankjordan/bevy_save#34]
I'll put up a PR for it at some point, I doubt there's anything too significant for this plugin, but wanted to highlight that we're behind a version.

**Comment by hankjordan** [comment]
I have made the changes, but have not been able to test yet. I will push a full release this weekend.
https://github.com/hankjordan/bevy_save/commit/b6cf516e07f674c1bcc0808637aff6ec381a874f

**Comment by MeoMix** [comment]
Sounds good. The changes look pretty safe :)
